### ISSUE TITLE
Unclear question of this keyword

### ISSUE THREAD

**Issue by WillBeethoven** [udacity/fend-issues#187]
![screen shot 2018-04-20 at 10 46 26](https://user-images.githubusercontent.com/14329786/39028233-1f657950-4488-11e8-8328-dd349d8cbd30.png)

Base on the correct answer, we should declare `this` is a keyword rather than a string in `console.log()`.

For example: **..., what is the value of the keyword `this`?**

**Comment by hbkwong** [comment]
Hi @WillBeethoven, thanks for checking in. Just wanted to get more details on this one. Exactly where did you encounter this snippet? I can't seem to access the screenshot/attachment at the beginning of your post.

**Comment by WillBeethoven** [comment]
Hi @hbkwong, I've updated the picture.

**Comment by hbkwong** [comment]
Hey @WillBeethoven, thanks for updating the photo. I can see how a student may be misguided by how the question is worded. While the solution remains (i.e.,  `myFunction` is still called "function-style" and therefore `this` is the global object), I'll make the update in the classroom to reflect the _keyword_ `this` rather than the string. Thanks for reaching out!
