### ISSUE TITLE
Arcade Game Project Zip File

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#210]
I'm trying to work on classic arcade game project, I have downloaded the zip file from this link :

https://www.google.com/url?q=https://github.com/udacity/frontend-nanodegree-arcade-game&sa=D&ust=1496438325981000&usg=AFQjCNHZChhjotWSnxbqtSYsHnkg_jEkog_

https://github.com/udacity/frontend-nanodegree-arcade-game

But normally I have to see the game loaded when I open index.html , instead I see a blank page , please what is the problem ?

Ticket #: 805691

**Comment by MOhammedRiaad** [comment]
the problem is that you need to fix the js errors in the chrome devtools as its your first step to run the game , when you fix these errors all things will work on screen .

**Comment by KatyaHorton** [comment]
Hello, Jessica! 

Could you please let me know if you fixed the problem? 

Its been a day I am trying, making research on google and forum, asking my friends etc, but cant make it work :( 

If you could suggest me how to display the canvas instead of the blank page I would really appreciate :)  

Thank you

**Comment by KatyaHorton** [comment]
AH, done finally!

For those who struggle, all I had to go is to define `Player` constructor function, create an object `player` based on the constructor function, than create an `update()` method as a prototype of `Player` ;)
