### ISSUE TITLE
Adding instructions for Mac users- Git

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#53]
https://classroom.udacity.com/nanodegrees/nd001/parts/516663e9-a691-4993-8872-bee0a05033a5/modules/cbdbf249-3d40-4ffd-9cf6-38ed8940dbf2/lessons/1cc90ac3-c03a-43e6-8556-dcbd40dfd418/concepts/bda4a9b5-46e3-4ce9-b58d-90eded438522

Installing Git:
A student requested that we add installation instructions for Mac users such as this website:
https://modulesunraveled.com/installing-git/installing-git-if-you-do-not-have-xcode-or-command-line-developer-tools-installed

Ticket #:586902

**Comment by richardkalehoff** [comment]
This isn't needed because there are messages that this is Windows only in multiple places. Beneath the video there's the text:

> *Reminder: This page is Windows-only! Mac and Linux users, skip ahead to the next page!*

Also, right at the beginning of the video, Karl tells students that they can skip to the next page if they're using Mac or Linux."

Lastly, the title of the concept is "Windows: Installing Git Bash".

**Comment by JessicaBettencourt** [comment]
Thanks for clarifying Richard!
