### ISSUE TITLE
General Feedback Pixel Art Maker

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fend-issues#97]
This does not sound like it can be an immediate fix, but just wanted to pass along the feedback about this section:

"I am at the end of section 2 dealing with pixel maker and the project.

I wanted to say that there is a sharp jump from the intro section to this one. All of the previous sections have good little mini programming challenges. Way more “active learning’. In the second section, the questions are a little more multiple choice, or single-line oriented. And then you get hit with pixel maker, When using js with forms not really covered anywhere. 

I would like to see more mini-programming exercises, I think they are more effective. There are some screens that have clear errors.. mostly btw querySelector and querySelectorAll. I have to re-read some stuff, will try to catch them again."

Ticket #670354

**Comment by dwiehoff** [comment]
I was fine with the pixel maker project. I am completely overwhelmed with using flexbox for the portfolio site. It came out of nowhere and somehow I cannot find any resources that would help me along. During the course it's all a piece of cake and then suddenly you are hit with sorcery :P

**Comment by hbkwong** [comment]
Closing out old issues. Saw the issues regarding `querySelector` and `querySelectorAll ` in previous tickets (if I recall correctly, in quizzes) which have since been resolved.

@dwiehoff, I'd love to get your two cents on your experience on Build a Portfolio Site! Feel free to reach out to me directly in Slack, or even post in the #feedback channel.
